services:
  - type: web
    name: stim-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ADMIN_PASS
        value: admin123
      - key: ADMIN_IDS
        value: 7592032451
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
